language: python
python:
  - "3.7"

install:
    - pip install -U pip
    - pip install -U setuptools
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - python setup.py develop

before_script:
    - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

jobs:
    include:
        - stage: test
          name: test
          script: python setup.py test
        - stage: fossa
          # FOSSA_API_KEY unavailable for pull requests
          # https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions
          if: fork = false
          name: fossa
          script:
              # NOTE: before running `fossa` make sure to save your FOSSA_API_KEY in your
              # environment variable in Travis see below.
              - fossa init
              - fossa analyze
        - stage: deploy
          script: skip
          deploy:
            provider: pypi
            # tmp workaround from travis CI
            # https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494/10
            install: pip install keyring==21.4.0
            username: "__token__"
            password: $PYPI_API_TOKEN
            on:
              tags: true
            skip_existing: true
            distributions: "sdist bdist_wheel"

after_success:
    - fossa test